# permissions for end users to edit helloworldmanagers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: helloworldmanager-editor-role
rules:
- apiGroups:
  - example.com.example.com
  resources:
  - helloworldmanagers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - example.com.example.com
  resources:
  - helloworldmanagers/status
  verbs:
  - get
